# The Simpsons Game Recomp — PS5 cross toolchain.
#
# FreeBSD is used only as CMake's closest public-SDK target model. ReXGlue gets
# an explicit REXGLUE_PS5 identity and must not infer Linux UI/runtime services.

if(NOT DEFINED ENV{PS5_PAYLOAD_SDK})
  message(FATAL_ERROR "PS5_PAYLOAD_SDK is not set")
endif()
if(NOT DEFINED ENV{NATIVE_EMUS_ROOT})
  message(FATAL_ERROR "NATIVE_EMUS_ROOT is not set")
endif()

set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang")
set(CMAKE_CXX_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang++")
set(CMAKE_AR "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ar")
set(CMAKE_RANLIB "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ranlib")

set(CMAKE_FIND_ROOT_PATH "$ENV{PS5_PAYLOAD_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(PKG_CONFIG_EXECUTABLE "/bin/false" CACHE FILEPATH "" FORCE)

set(REXGLUE_PS5 ON CACHE BOOL "" FORCE)
set(PS5RT_BUILD_PS5_BACKEND ON CACHE BOOL "" FORCE)
set(REXGLUE_ENABLE_TRACY OFF CACHE BOOL "" FORCE)
set(REXGLUE_ENABLE_PERF_COUNTERS ON CACHE BOOL "" FORCE)
set(REXGLUE_ENABLE_FIDELITYFX OFF CACHE BOOL "" FORCE)
set(REXGLUE_USE_D3D12 OFF CACHE BOOL "" FORCE)
set(REXGLUE_USE_VULKAN ON CACHE BOOL "" FORCE)

set(NATIVE_EMUS_ROOT "$ENV{NATIVE_EMUS_ROOT}" CACHE PATH "" FORCE)

set(_PS5_ZEN2 "-march=znver2 -msse4.1 -mavx2 -mno-vzeroupper")
set(CMAKE_C_FLAGS_INIT "-O2 -fPIC ${_PS5_ZEN2}")
set(CMAKE_CXX_FLAGS_INIT "-O2 -fPIC ${_PS5_ZEN2}")
