# NATIVE-EMUS-PS5: PPSSPP engine-only PS5 toolchain.
# Produces x86_64-sie-ps5 static engine archives. No libretro module.

if(NOT DEFINED ENV{PS5_PAYLOAD_SDK})
  message(FATAL_ERROR "PS5_PAYLOAD_SDK is not set")
endif()
if(NOT DEFINED ENV{NATIVE_EMUS_ROOT})
  message(FATAL_ERROR "NATIVE_EMUS_ROOT is not set")
endif()

set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang")
set(CMAKE_CXX_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang++")
set(CMAKE_AR "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ar")
set(CMAKE_RANLIB "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ranlib")

set(CMAKE_FIND_ROOT_PATH "$ENV{PS5_PAYLOAD_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(PPSSPP_PS5 ON CACHE BOOL "" FORCE)
set(USING_X11_VULKAN OFF CACHE BOOL "" FORCE)

set(PS5RT_INCLUDE "-I$ENV{NATIVE_EMUS_ROOT}/runtime/include")
set(PS5_ZEN2 "-march=znver2 -msse4.1 -mavx2 -mno-vzeroupper")

set(CMAKE_C_FLAGS_INIT "-O2 -fPIC -w -Dstatic_assert=_Static_assert -DZSTD_TRACE=0 ${PS5RT_INCLUDE} ${PS5_ZEN2}")
set(CMAKE_CXX_FLAGS_INIT "-O2 -fPIC -w -DZSTD_TRACE=0 ${PS5RT_INCLUDE} ${PS5_ZEN2}")
