# NATIVE-EMUS-PS5: standalone Dolphin PS5 engine toolchain.
# The target remains Dolphin's x86-64 Jit64 + fastmem; no interpreter final mode.

if(NOT DEFINED ENV{PS5_PAYLOAD_SDK})
  message(FATAL_ERROR "PS5_PAYLOAD_SDK is not set")
endif()
if(NOT DEFINED ENV{NATIVE_EMUS_ROOT})
  message(FATAL_ERROR "NATIVE_EMUS_ROOT is not set")
endif()

set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang")
set(CMAKE_CXX_COMPILER "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-clang++")
set(CMAKE_AR "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ar")
set(CMAKE_RANLIB "$ENV{PS5_PAYLOAD_SDK}/bin/prospero-ranlib")

set(CMAKE_FIND_ROOT_PATH "$ENV{PS5_PAYLOAD_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PKG_CONFIG_EXECUTABLE "/bin/false" CACHE FILEPATH "" FORCE)

set(DOLPHIN_PS5 ON CACHE BOOL "" FORCE)

set(PS5RT_INCLUDE "-I$ENV{NATIVE_EMUS_ROOT}/runtime/include")
set(PS5_ZEN2 "-march=znver2 -msse4.1 -mavx2 -mno-vzeroupper")
set(CMAKE_C_FLAGS_INIT "-O2 -fPIC -w ${PS5RT_INCLUDE} ${PS5_ZEN2}")
set(CMAKE_CXX_FLAGS_INIT "-O2 -fPIC -w ${PS5RT_INCLUDE} ${PS5_ZEN2}")
